name: Run tests
on:
  push:
    branches: ["main", "test-ci"]
  pull_request:
    branches: ["main", "test-ci"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: |
            package.json
          node-version: "18.x"
          cache: "npm"
      - run: npm install
      - run: npm test
