name: Run tests
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: |
            package.json
          node-version: "18.x"
          cache: "npm"
      - run: npm ci
      - name: Install dependencies in all examples
        run: |
          for dir in examples/*/; do
            if [ -f "$dir/package.json" ]; then
              if [ -f "$dir/package-lock.json" ]; then
                npm ci --prefix "$dir"
              else
                npm i --prefix "$dir"
              fi
            fi
          done
      - run: npm test
